-- Manually-entered monthly ad spend per lead source; drives the source ROI
-- table on Consolidated Reports (cost per enrollment, revenue multiple).
create table if not exists public.ad_spend (
  id bigint generated by default as identity primary key,
  month text not null check (month ~ '^\d{4}-\d{2}$'),
  source text not null,
  amount numeric not null default 0 check (amount >= 0),
  updated_by text,
  updated_at timestamptz not null default now(),
  unique (month, source)
);

alter table public.ad_spend enable row level security;
